Add steps, parallel & cleaned up unnecessary bits.

diff --git a/nanocd b/nanocd
--- a/nanocd
+++ b/nanocd
@@ -1,50 +1,48 @@
 #!/bin/bash
-
 # NanoCD
 
 set -o pipefail
 set -o nounset
 
+
 # Defaults
 FORCE=0
 VERBOSE=0
-REPO=""
-EMAIL=""
-NAME="ci"
-TEST_DIR="."
-TEST_COMMAND="./test.sh"
-MAIL_CMD="mail"
+REPO=""                                 # Set with -r option or can be hard-coded here
+LOCAL_CHECKOUT=""                       # Set with -l option or can be hard-coded here
+EMAIL="your@email.tld"
+PROJECT_NAME="project_name"
+TEST_DIR="tests"
+TEST_COMMAND="parallel ::: ./test*"     # Install parallel with 'brew install parallel'
+MAIL_CMD="sendmail"
 MAIL_CMD_ATTACH_FLAG="-A"
-MAIL_CMD_RECIPIENTS_FLAG="-t"
-MAIL_CMD_SUBJECT_FLAG="-s"
-PRE_SCRIPT="/bin/true"
-POST_SCRIPT="/bin/true"
+BUILD_SCRIPT=""
+DEPLOY_SCRIPT=""
 TIMEOUT_S=86400
+PAGER=${PAGER:-less}
 
-PAGER=${PAGER:-more}
 
+# Help function
 function show_help() {
 	cat > /dev/stdout << END
-${0} -r <repo> -l <local_checkout> [-q <pre-script>] [-w <post-script>]
+${0} -r <repo> -l <local_checkout> [-b <build-script>] [-w <post-script>]
    [-m <email>] [-a <mail command>] [-t <mail command attach flag>]
    [-s <mail command subject flag] [-e <recipients flag>] [-n name] [-d <dir>] 
    [-c <command>] [-f] [-v] [-h]
 
 REQUIRED ARGS:
--r - git repository, eg https://github.com/myname/myproj (required)
+-r - git repository, eg https://github.com/myname/myproj.git (required)
 -l - local checkout of code (that gets updated to determine whether a run is needed) (required)
 
 OPTIONAL ARGS:
--q - script to run just before actually performing test (default ${PRE_SCRIPT})
--w - script to run just after actually performing test (default ${POST_SCRIPT})
+-b - build script to run (default $BUILD_SCRIPT)
+-w - script to run just after actually performing test (default $DEPLOY_SCRIPT)
 -m - email address to send to using "mail" command (default logs to stdout)
--a - mail command to use (default=${MAIL_CMD})
--n - name for ci (unique, must be a valid directory name), eg myproj (default=${NAME})
--d - directory within repository to navigate to (default=${TEST_DIR})
--c - test command to run from -d directory (default=${TEST_COMMAND})
--t - attach argument flag for mail command (default=${MAIL_CMD_ATTACH_FLAG}, empty string means no-attach)
--s - subject flag for mail command (default=${MAIL_CMD_RECIPIENTS_FLAG})
--e - recipients flag (default=${MAIL_CMD_RECIPIENTS_FLAG}, empty string means no flag needed)
+-a - mail command to use (default=$MAIL_CMD)
+-n - name for ci (unique, must be a valid directory name), eg myproj (default=$PROJECT_NAME)
+-d - directory within repository that contains test scripts (default=$TEST_DIR)
+-c - test command to run from -d directory (default=$TEST_COMMAND)
+-t - attach argument flag for mail command (default=$MAIL_CMD_ATTACH_FLAG, empty string means no-attach)
 -f - force a run even if repo has no updates (default off)
 -v - verbose logging (default off)
 -i - timeout in seconds (default 86400, ie one day, does KILL one hour after that)
@@ -52,147 +50,161 @@ OPTIONAL ARGS:
 
 EXAMPLES
 
-- "Clone -r https://github.com/4-9s/sessh.git if a git pull on /space/git/sessh indicates there's been an update.
-  Then navigate to test, run ./test.sh and mail yo@tkjef.com if there are any issues"
+- "Clone -r https://github.com/myname/myproj.git if a git fetch on /path/to/git/root/ indicates there's been an update.
+  Then navigate to tests (default), run ./test.sh and mail your@email.tld after successfull or failed completion with results"
 
-  ./nanocd -r https://github.com/4-9s/sessh.git -l /space/git/sessh -d test -c ./test.sh -m yo@tkjef.com
-
+  nanocd -r https://github.com/myname/myproj.git -l /path/to/git/root/ -d tests -c ./test.sh -m your@email.tld
+  nanocd -r https://github.com/myname/myproj.git -l /path/to/git/root/ -m your@email.tld
+  nanocd -r https://github.com/myname/myproj.git -l /path/to/git/root/
 
 - "Run this continuously in a crontab."
 
-  Crontab line:
-
-  * * * * * cd /path/to/nanocd && ./nanocd -r https://github.com/4-9s/sessh.git -l /space/git/sessh -d test -c ./test.sh -m yo@tkjef.com
+  Crontab line to run every 30 min:
+  0,30 * * * * nanocd -r https://github.com/myname/myproj.git -l /path/to/git/root/
 END
 }
 
 
-while getopts "h?vfm:n:d:r:l:c:a:q:w:t:e:s:" opt
+# Override defaults with commandline flags + options/arguments
+while getopts "h?vfm:n:d:r:l:c:a:b:w:t:e:s:" opt
 do
-	case "${opt}" in
+	case $opt in
 	h|\?)
 		show_help
 		exit 0
 		;;
 	v) VERBOSE=1 ;;
 	f) FORCE=1 ;;
-	r) REPO=${OPTARG} ;;
-	m) EMAIL=${OPTARG} ;;
-	n) NAME=${OPTARG} ;;
-	d) TEST_DIR=${OPTARG} ;;
-	l) LOCAL_CHECKOUT=${OPTARG} ;;
-	c) TEST_COMMAND=${OPTARG} ;;
-	q) PRE_SCRIPT=${OPTARG} ;;
-	w) POST_SCRIPT=${OPTARG} ;;
-	a) MAIL_CMD=${OPTARG} ;;
-	t) MAIL_CMD_ATTACH_FLAG=${OPTARG} ;;
-	e) MAIL_CMD_RECIPIENTS_FLAG=${OPTARG} ;;
-	s) MAIL_CMD_SUBJECT_FLAG=${OPTARG} ;;
-	i) TIMEOUT_S=${OPTARG} ;;
+	r) REPO=$OPTARG ;;
+	m) EMAIL=$OPTARG ;;
+	n) PROJECT_NAME=$OPTARG ;;
+	d) TEST_DIR=$OPTARG ;;
+	l) LOCAL_CHECKOUT=$OPTARG ;;
+	c) TEST_COMMAND=$OPTARG ;;
+	b) BUILD_SCRIPT=$OPTARG ;;
+	w) DEPLOY_SCRIPT=$OPTARG ;;
+	a) MAIL_CMD=$OPTARG ;;
+	t) MAIL_CMD_ATTACH_FLAG=$OPTARG ;;
+	i) TIMEOUT_S=$OPTARG ;;
 	esac
 done
-
 shift "$((OPTIND-1))"
 
-if [[ ${REPO} = "" ]]
+
+# If no repo specified, then show_help
+if [[ $REPO = "" ]]
 then
 	show_help
 	exit 1
 fi
 
 
-# To force a run even if no updates.
-
-if [[ ${VERBOSE} -gt 0 ]]
+# To show all executed commands in standard output.
+# Off by default, set -v flag to enable
+if [[ $VERBOSE -gt 0 ]]
 then
 	set -x
 fi
 
-BUILD_DIR_BASE="/tmp/${NAME}"
-BUILD_DIR="${BUILD_DIR_BASE}/${NAME}_builddir"
-mkdir -p "${BUILD_DIR}"
-LOG_FILE="${BUILD_DIR}/${NAME}_build_${RANDOM}.log.txt"
-BUILD_LOG_FILE="${BUILD_DIR}/${NAME}_build.log.txt"
-LOCK_FILE="${BUILD_DIR}/${NAME}_ci.lck"
 
+# Temporary build directory, log file & lock file
+BUILD_DIR_BASE="/tmp/nanocd"
+BUILD_DIR="${BUILD_DIR_BASE}/builddir/"
+mkdir -p $BUILD_DIR
+LOG_FILE="${BUILD_DIR}/${PROJECT_NAME}_build_${RANDOM}.log.txt"
+BUILD_LOG_FILE="${BUILD_DIR}/${PROJECT_NAME}_build.log.txt"
+LOCK_FILE="${BUILD_DIR}/${PROJECT_NAME}_cd.lck"
+
+
+# Common functions
 function cleanup() {
-	rm -rf "${BUILD_DIR}"
-	rm -f "${LOCK_FILE}"
-	# get rid of /tmp detritus, leaving anything accessed 2 days ago+
-	find "${BUILD_DIR_BASE}"/* -type d -atime +1 -exec rm {} -rf +
-	echo "cleanup done"
+    rm -rf $BUILD_DIR
+    rm -f $LOCK_FILE
+    # get rid of /tmp detritus, leaving anything accessed 2 days ago+
+    find $BUILD_DIR_BASE -type d -atime +1 | xargs rm -rf
+    echo $msg
+    echo "cleanup done"
 }
 
 function send_mail() {
-	msg=${1}
-	if [[ ${LOG_FILE} != "" ]] && [[ ${MAIL_CMD_ATTACH_FLAG} != "" ]]
+	msg=$@
+	if [[ $LOG_FILE != "" ]] && [[ $MAIL_CMD_ATTACH_FLAG != "" ]]
 	then
-		log_file_arg=(${MAIL_CMD_ATTACH_FLAG} ${LOG_FILE})
+		log_file_arg=($MAIL_CMD_ATTACH_FLAG $LOG_FILE)
 	fi
-	if [[ ${EMAIL} != "" ]] && [[ ${MAIL_CMD} != "" ]]
+	if [[ $EMAIL != "" ]] && [[ $MAIL_CMD != "" ]]
 	then
-		echo "${msg}" | ${MAIL_CMD} "${MAIL_CMD_SUBJECT_FLAG}" "${msg}" "${log_file_arg[@]}" "${MAIL_CMD_RECIPIENTS_FLAG}" "${EMAIL}"
+        echo $msg | $MAIL_CMD $msg $log_file_arg[@] $EMAIL
 	else
-		echo "${msg}"
+		echo "Email sending FAILED."
 	fi
 }
 
-date 2>&1 | tee -a "${BUILD_LOG_FILE}"
 
-# Lockfile
-if [[ -a ${LOCK_FILE} ]]
+# Add date to build log file, check lock file exists
+date 2>&1 | tee -a $BUILD_LOG_FILE
+if [[ -a $LOCK_FILE ]]
 then
-	echo "Already running" | tee -a "${BUILD_LOG_FILE}"
+	echo "Already running" | tee -a $BUILD_LOG_FILE
 	exit 
 fi
 
+
+# Runs cleanup function if receive below SIGNAL_SPEC
 trap cleanup TERM INT QUIT EXIT
 
-touch "${LOCK_FILE}"
-# Fetch changes
-pushd "${LOCAL_CHECKOUT}"
-git fetch origin master 2>&1 | tee -a "${BUILD_LOG_FILE}"
-# See if there are any incoming changes
+
+# Step #1: Check if there are any new merged pull requests on the remote master branch
+touch $LOCK_FILE
+cd $LOCAL_CHECKOUT
+git fetch origin master 2>&1 | tee -a $BUILD_LOG_FILE
 updates=$(git log HEAD..origin/master --oneline | wc -l)
-echo "Updates: ${updates}" | tee -a "${BUILD_LOG_FILE}"
-if [[ ${updates} -gt 0 ]] || [[ ${FORCE} -gt 0 ]]
+echo "Updates: $updates" | tee -a $BUILD_LOG_FILE
+
+
+# If there are updates pull them down, build, deploy + test.
+if [[ $updates -gt 0 ]] || [[ $FORCE -gt 0 ]]
 then
-	touch "${LOG_FILE}"
-	pushd "${LOCAL_CHECKOUT}"
-	echo "Pulling" | tee -a "${LOG_FILE}"
-	git pull origin master 2>&1 | tee -a "${LOG_FILE}"
-	popd
-	# This won't exist in a bit so no point pushd'ing
-	pushd "${BUILD_DIR}"
-	# Clone to NAME
-	git clone "${REPO}" "${NAME}"
-	popd
-	${PRE_SCRIPT} 2>&1 | tee -a "${LOG_FILE}"
-	EXIT_CODE="${?}"
-        if [[ ${EXIT_CODE} -ne 0 ]]
+	touch $LOG_FILE
+
+    # Step #2: In local repo master branch update with latest changes
+	echo "Pulling" | tee -a $LOG_FILE
+	git pull origin master 2>&1 | tee -a $LOG_FILE
+
+	# Step #3: In /tmp build directory, clone to PROJECT_NAME, run build script
+	cd $BUILD_DIR
+	git clone $REPO $PROJECT_NAME
+	$BUILD_SCRIPT 2>&1 | tee -a $LOG_FILE
+    if [[ $? -ne 0 ]]
 	then
-		msg="ANGRY ${NAME} on $(hostname)"
+		msg="Build script for project:$PROJECT_NAME on host:$(hostname) FAILED"
+	    echo $msg
 	fi
-	pushd "${BUILD_DIR}"/"${NAME}"/"${TEST_DIR}"
-	timeout "${TIMEOUT_S}" "${TEST_COMMAND}" 2>&1 | tee -a "${LOG_FILE}"
-	EXIT_CODE=$?
-	popd
-        if [[ ${EXIT_CODE} -ne 0 ]]
+
+    # Step #4: Run deploy script
+	$DEPLOY_SCRIPT 2>&1 | tee -a "$LOG_FILE"
+    if [[ $? -ne 0 ]]
 	then
-		if [[ ${EXIT_CODE} -eq 124 ]]
+		msg="Deploy script for project:$PROJECT_NAME on host:$(hostname) FAILED"
+	    echo $msg
+	fi
+
+    # Step #5: Run test script(s)
+	cd "${BUILD_DIR}${PROJECT_NAME}/${TEST_DIR}"
+	gtimeout $TIMEOUT_S $TEST_COMMAND 2>&1 | tee -a $LOG_FILE # Install gtimeout with 'brew install coreutils'
+	EXIT_CODE=$?
+    if [[ $EXIT_CODE -ne 0 ]]
+	then
+		if [[ $EXIT_CODE -eq 124 ]]
 		then
-			msg="ANGRY (TIMEOUT) ${NAME} on $(hostname)"
+			msg="Tests (TIMEOUT) for project:$PROJECT_NAME on host:$(hostname)"
+	        echo $msg
 		else
-			msg="ANGRY ${NAME} on $(hostname)"
+			msg="Tests for project:$PROJECT_NAME on host:$(hostname) FAILED"
+	        echo $msg
 		fi
 	else
-		msg="HAPPY ${NAME} on $(hostname)"
+        msg="Build, deploy & tests for project:$PROJECT_NAME on host:$(hostname) SUCCESSFUL"
 	fi
-	${POST_SCRIPT} 2>&1 | tee -a "${LOG_FILE}"
-	EXIT_CODE=$?
-        if [[ ${EXIT_CODE} -ne 0 ]]
-	then
-		msg="ANGRY ${NAME} on $(hostname)"
-	fi
-	send_mail "${msg}"
+    send_mail $msg
 fi
