formatting fixes

diff --git a/nanocd b/nanocd
--- a/nanocd
+++ b/nanocd
@@ -24,7 +24,7 @@ PAGER=${PAGER:-less}
 
 # Help function
 function show_help() {
-	cat > /dev/stdout << END
+cat > /dev/stdout << END
 ${0} -r <repo> -l <local_checkout> [-b <build-script>] [-w <post-script>]
    [-m <email>] [-a <mail command>] [-t <mail command attach flag>]
    [-s <mail command subject flag] [-e <recipients flag>] [-n name] [-d <dir>] 
@@ -68,25 +68,25 @@ END
 # Override defaults with commandline flags + options/arguments
 while getopts "h?vfm:n:d:r:l:c:a:b:w:t:e:s:" opt
 do
-	case $opt in
-	h|\?)
-		show_help
-		exit 0
-		;;
-	v) VERBOSE=1 ;;
-	f) FORCE=1 ;;
-	r) REPO=$OPTARG ;;
-	m) EMAIL=$OPTARG ;;
-	n) PROJECT_NAME=$OPTARG ;;
-	d) TEST_DIR=$OPTARG ;;
-	l) LOCAL_CHECKOUT=$OPTARG ;;
-	c) TEST_COMMAND=$OPTARG ;;
-	b) BUILD_SCRIPT=$OPTARG ;;
-	w) DEPLOY_SCRIPT=$OPTARG ;;
-	a) MAIL_CMD=$OPTARG ;;
-	t) MAIL_CMD_ATTACH_FLAG=$OPTARG ;;
-	i) TIMEOUT_S=$OPTARG ;;
-	esac
+    case $opt in
+        h|\?)
+            show_help
+            exit 0
+            ;;
+        v) VERBOSE=1 ;;
+        f) FORCE=1 ;;
+        r) REPO=$OPTARG ;;
+        m) EMAIL=$OPTARG ;;
+        n) PROJECT_NAME=$OPTARG ;;
+        d) TEST_DIR=$OPTARG ;;
+        l) LOCAL_CHECKOUT=$OPTARG ;;
+        c) TEST_COMMAND=$OPTARG ;;
+        b) BUILD_SCRIPT=$OPTARG ;;
+        w) DEPLOY_SCRIPT=$OPTARG ;;
+        a) MAIL_CMD=$OPTARG ;;
+        t) MAIL_CMD_ATTACH_FLAG=$OPTARG ;;
+        i) TIMEOUT_S=$OPTARG ;;
+    esac
 done
 shift "$((OPTIND-1))"
 
@@ -94,8 +94,8 @@ shift "$((OPTIND-1))"
 # If no repo specified, then show_help
 if [[ $REPO = "" ]]
 then
-	show_help
-	exit 1
+    show_help
+    exit 1
 fi
 
 
@@ -103,7 +103,7 @@ fi
 # Off by default, set -v flag to enable
 if [[ $VERBOSE -gt 0 ]]
 then
-	set -x
+    set -x
 fi
 
 
@@ -126,17 +126,17 @@ function cleanup() {
 }
 
 function send_mail() {
-	msg=$@
-	if [[ $LOG_FILE != "" ]] && [[ $MAIL_CMD_ATTACH_FLAG != "" ]]
-	then
-		log_file_arg=($MAIL_CMD_ATTACH_FLAG $LOG_FILE)
-	fi
-	if [[ $EMAIL != "" ]] && [[ $MAIL_CMD != "" ]]
-	then
+    msg=$@
+    if [[ $LOG_FILE != "" ]] && [[ $MAIL_CMD_ATTACH_FLAG != "" ]]
+    then
+        log_file_arg=($MAIL_CMD_ATTACH_FLAG $LOG_FILE)
+    fi
+    if [[ $EMAIL != "" ]] && [[ $MAIL_CMD != "" ]]
+    then
         echo $msg | $MAIL_CMD $msg $log_file_arg[@] $EMAIL
-	else
-		echo "Email sending FAILED."
-	fi
+    else
+        echo "Email sending FAILED."
+    fi
 }
 
 
@@ -144,8 +144,8 @@ function send_mail() {
 date 2>&1 | tee -a $BUILD_LOG_FILE
 if [[ -a $LOCK_FILE ]]
 then
-	echo "Already running" | tee -a $BUILD_LOG_FILE
-	exit 
+    echo "Already running" | tee -a $BUILD_LOG_FILE
+    exit 
 fi
 
 
@@ -164,7 +164,7 @@ echo "Updates: $updates" | tee -a $BUILD_LOG_FILE
 # If there are updates pull them down, build, deploy + test.
 if [[ $updates -gt 0 ]] || [[ $FORCE -gt 0 ]]
 then
-	touch $LOG_FILE
+    touch $LOG_FILE
 
     # Step #2: In local repo master branch update with latest changes
     echo "Pulling" | tee -a $LOG_FILE
@@ -178,7 +178,7 @@ then
 	then
 		msg="Build script for project:$PROJECT_NAME on host:$(hostname) FAILED"
 	    echo $msg
-	fi
+    fi
 
     # Step #4: Run deploy script
     $DEPLOY_SCRIPT 2>&1 | tee -a "$LOG_FILE"
@@ -186,7 +186,7 @@ then
 	then
 		msg="Deploy script for project:$PROJECT_NAME on host:$(hostname) FAILED"
 	    echo $msg
-	fi
+    fi
 
     # Step #5: Run test script(s)
     cd "${BUILD_DIR}${PROJECT_NAME}/${TEST_DIR}"
